# Generated by Django 5.1.2 on 2024-10-22 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nascimento', models.DateField()),
                ('rg', models.CharField(blank=True, max_length=50, null=True)),
                ('local_nascimento', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('curso', models.CharField(max_length=50)),
                ('link_lattes', models.URLField(blank=True, null=True)),
                ('data_matricula', models.DateField(blank=True, null=True)),
                ('data_aprovacao_exame_qualificacao', models.DateField(blank=True, null=True)),
                ('data_aprovacao_exame_proficiencia', models.DateField(blank=True, null=True)),
                ('data_limite_deposito_trabalho', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('professor', models.CharField(max_length=255)),
                ('numero_alunos', models.IntegerField()),
                ('periodo', models.CharField(max_length=50)),
                ('semestre', models.CharField(max_length=50)),
                ('sala', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('semestre', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('houve_reavaliacao', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Relatorio',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_matricula', models.CharField(max_length=50, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
            ],
            options={
                'db_table': 'Aluno',
            },
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
            ],
            options={
                'db_table': 'Comissao',
            },
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
                ('numero_alunos_orientados', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Orientador',
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Avaliando', 'Avaliando'), ('Fechado', 'Fechado')], max_length=50)),
                ('data_abertura', models.DateField()),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.relatorio')),
            ],
            options={
                'db_table': 'Chamado',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer', models.TextField()),
                ('conceito', models.CharField(choices=[('Adequado', 'Adequado'), ('Adequado com Ressalvas', 'Adequado com Ressalvas'), ('Insatisfatório', 'Insatisfatório')], max_length=50)),
                ('data_avaliacao', models.DateField()),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.relatorio')),
            ],
            options={
                'db_table': 'Avaliacao',
            },
        ),
        migrations.AddField(
            model_name='relatorio',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno'),
        ),
        migrations.CreateModel(
            name='HistoricoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
            ],
            options={
                'db_table': 'HistoricoDisciplina',
            },
        ),
        migrations.CreateModel(
            name='RelatorioDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_limite', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('conceito_orientador', models.CharField(blank=True, max_length=50, null=True)),
                ('conceito_comissao', models.CharField(blank=True, max_length=50, null=True)),
                ('houve_reavaliacao', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
                ('comissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comissao')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orientador')),
            ],
            options={
                'db_table': 'RelatorioDesempenho',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orientador'),
        ),
    ]
