# Generated by Django 4.2.14 on 2024-10-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(related_name='alunos', to='core.disciplina'),
        ),
    ]
