# Generated by Django 4.2.16 on 2024-12-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_avaliacao_relatorio_avaliacao_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='periodo',
            field=models.CharField(choices=[('Noturno', 'Noturno'), ('Diurno', 'Diurno'), ('Matutino', 'Matutino'), ('Integral', 'Integral')], max_length=50),
        ),
    ]
